### ISSUE TITLE
Please add the description!

### ISSUE THREAD

**Issue by Snuggle** [JamesJ/timeformatter#1]
Please just copy/paste this line into the description.
![image](https://user-images.githubusercontent.com/26250962/31540125-a760ff7a-b002-11e7-8062-82df9e5ea7ed.png)

It will fix the spooky blank space on your GitHub profile. 👻🎃
![image](https://user-images.githubusercontent.com/26250962/31540219-f1fbdad2-b002-11e7-98e3-b0aa790cd071.png)*

*Image blurred for dramatic effect.

You could also do this for these other pinned repositories. I'm not going to make a separate issue for each.

📌
[https://github.com/JamesJ/SimpleMoneyCalculator](SimpleMoneyCalculator)
[https://github.com/JamesJ/BungeeStaffChat](BungeeStaffChat)

**Comment by JamesJ** [comment]
Done.
